Item.create(name: "Guitar Pick", points: 5)
Item.create(name: "Tie Dye Shirt", points: 10)
Item.create(name: "China Cat Sunflower", points: 15)
Item.create(name: "Steal Your Face", points: 20)
Item.create(name: "Scarlet Begonia", points: 25)
